name: Testes Unitários e dados

runs:
  using: composite
  steps:
    - name: Instalar dependencias
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ".[dev]"

    - name: Executar testes unitarios
      shell: bash
      run: python -m pytest
